[tool.poetry]
name = "bolt"
version = "0.1.0"
description = ""
authors = ["Dave Gaeddert <dave.gaeddert@dropseed.dev>"]
# readme = "README.md"

packages = [
    { include = "bolt" },
]

[tool.poetry.scripts]
bolt = "bolt.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
sqlparse = ">=0.3.1"
jinja2 = "^3.1.2"
python-dotenv = "^1.0.0"
cryptography = "^41.0.3"


[tool.poetry.group.dev.dependencies]
# Testing
pytest = "^7.4.2"
coverage = "^7.3.2"

# Formatting and linting
black = "^23.9.1"
ruff = "^0.0.292"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
