[tool.poetry]
name = "dx"
version = "0.0.0"
description = ""
authors = ["Dave Gaeddert <dave.gaeddert@gmail.com>", "Past authors of Django"]
readme = "README.md"

packages = [
    { include = "django" },
]

[tool.poetry.dependencies]
python = "^3.10"
asgiref = ">=3.6.0"
sqlparse = ">=0.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
