[tool.poetry]
name = "bolt"
version = "0.1.0"
description = ""
authors = ["Dave Gaeddert <dave.gaeddert@dropseed.dev>"]
# readme = "README.md"

packages = [
    { include = "bolt" },
]

[tool.poetry.scripts]
bolt = "bolt.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
jinja2 = "^3.1.2"
python-dotenv = "^1.0.0"
cryptography = "^41.0.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
coverage = "^7.3.2"
ruff = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py310"
ignore = [
    "E501",  # Never enforce `E501` (line length violations)
    "S101",  # pytest use of assert
]
extend-select = [
    "I",  # isort
    # # "C90",  # mccabe
    # # "N",  # pep8-naming
    "UP",  # pyupgrade
    # "S",  # bandit
    # # "B",  # bugbear
    "C4",  # flake8-comprehensions
    # # "DTZ",  # flake8-datetimez
    "ISC",  # flake8-implicit-str-concat
    # # "G",  # flake8-logging-format
    # # "T20",  # print
    "PT",  # pytest
]
