[tool.poetry]
name = "bolt"
version = "0.1.0"
description = ""
authors = ["Dave Gaeddert <dave.gaeddert@dropseed.dev>"]
readme = "README.md"

packages = [
    { include = "bolt" },
]

[tool.poetry.scripts]
bolt = "bolt.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
jinja2 = "^3.1.2"
python-dotenv = "^1.0.0"
cryptography = "^41.0.3"
click = ">=8.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
coverage = "^7.3.2"
ruff = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
extend = "bolt-code/bolt/code/ruff_defaults.toml"
target-version = "py310"
