[tool.poetry]
name = "bolt"
version = "0.1.0"
description = ""
authors = ["Dave Gaeddert <dave.gaeddert@dropseed.dev>"]
# readme = "README.md"

packages = [
    { include = "bolt" },
]

[tool.poetry.scripts]
bolt = "bolt.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
sqlparse = ">=0.3.1"
jinja2 = "^3.1.2"
python-dotenv = "^1.0.0"
rich = "^13.5.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
