# All built-in services will be defined in one file here,
# and you can select them using --profile
services:
  postgres:
    image: ${POSTGRES_DEV_IMAGE:-postgres:15}
    command: ${POSTGRES_DEV_COMMAND:-postgres -c stats_temp_directory=/tmp -c shared_preload_libraries=pg_stat_statements}
    restart: always
    volumes:
      - ${BOLT_TEMP_PATH}/dev/pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    profiles: ["postgres"]

  redis:
    image: ${REDIS_DEV_IMAGE:-redis:7}
    command: ${REDIS_DEV_COMMAND:-redis-server --save 60 1 --loglevel warning}
    restart: always
    volumes:
      - ${BOLT_TEMP_PATH}/dev/redis:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    profiles: ["redis"]
